---
permalink: deploy/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Você deve configurar os intervalos de tempo de armazenamento de acordo com as configurações recomendadas para Storage Replication Adapter (SRA) para ter um desempenho ideal em ambientes altamente dimensionados.' 
---
= Configure o Storage Replication Adapter para um ambiente altamente dimensionado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar os intervalos de tempo de armazenamento de acordo com as configurações recomendadas para Storage Replication Adapter (SRA) para ter um desempenho ideal em ambientes altamente dimensionados.



== Definições do fornecedor de armazenamento

Você deve definir os seguintes valores de tempo limite no SRM para ambiente escalado:

|===


| Definições avançadas | Valores de tempo limite 


 a| 
StorageProvider.Renúncia do Timeout
 a| 
Aumente o valor da definição de 900 segundos para 12000 segundos.



 a| 
StorageProvider.hostRescanDelaySec
 a| 
60



 a| 
StorageProvider.hostRescanRepeatCnt
 a| 
20



 a| 
StorageProvider.hostRescanTimeoutSec
 a| 
Defina um valor alto (por exemplo: 99999)

|===
Você também deve ativar a opção StorageProvider.autoResignatureMode.

Consulte a documentação da VMware para obter mais informações sobre como modificar as configurações do provedor de armazenamento.

https://docs.vmware.com/en/Site-Recovery-Manager/6.5/com.vmware.srm.admin.doc/GUID-E4060824-E3C2-4869-BC39-76E88E2FF9A0.html["Documentação do VMware vSphere: Altere as configurações do provedor de armazenamento"]



== Definições de armazenamento

Você deve definir o valor do intervalo de tempo limite storage.commandTimeout e storage.maxConcurrentCommandCnt para ambientes altamente dimensionados para 99.999 segundos.


NOTE: O intervalo de tempo limite especificado é o valor máximo. Não é necessário esperar que o tempo limite máximo seja atingido. A maioria dos comandos termina dentro do intervalo de tempo limite máximo definido.

Você também deve definir o tempo máximo para que o SRA execute uma única operação no arquivo vvol.properties: OFFTAP.operation.timeout.period.seconds=86400.

https://kb.netapp.com/mgmt/OTV/SRA/NetApp_Storage_Replication_Adapter_4.0%2F%2F7.X_for_ONTAP_Sizing_Guide["Resposta 1001111 da base de conhecimento da NetApp: Adaptador de replicação de armazenamento NetApp 4,0/7.X para Guia de dimensionamento de ONTAP"]

A documentação da VMware sobre como modificar as configurações do provedor de SAN tem mais informações.

https://docs.vmware.com/en/Site-Recovery-Manager/6.5/com.vmware.srm.admin.doc/GUID-711FD223-50DB-414C-A2A7-3BEB8FAFDBD9.html["Documentação do VMware Site Recovery Manager: Altere as configurações de armazenamento"]
