---
permalink: deploy/task_deploy_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: Você deve implantar as ferramentas do ONTAP em seu ambiente e especificar os parâmetros necessários para poder usar o dispositivo. 
---
= Como implantar ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve implantar as ferramentas do ONTAP em seu ambiente e especificar os parâmetros necessários para poder usar o dispositivo.

*O que você vai precisar*

* Você deve estar executando uma versão compatível do vCenter Server.
+

NOTE: As ferramentas do ONTAP podem ser registradas em uma implantação do vCenter Server ou em uma implantação do VMware vCenter Server Virtual Appliance (vCSA).

+
https://imt.netapp.com/matrix/imt.jsp?components=99343;&solution=1777&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade"]

* Você deve ter configurado e configurado seu ambiente do vCenter Server.
* Você deve ter configurado um host ESXi para sua máquina virtual.
* Você deve ter baixado o arquivo _.ova_.
* Você deve ter as credenciais de login de administrador para sua instância do vCenter Server.
* Você deve ter desconetado e fechado todas as sessões do navegador do vSphere Client e excluído o cache do navegador para evitar qualquer problema de cache do navegador durante a implantação de ferramentas do ONTAP.
* Você deve ter ativado o Internet Control Message Protocol (ICMP ).
+
Se o ICMP estiver desativado, a configuração inicial das ferramentas do ONTAP falhará e o VSC não poderá iniciar os serviços do VSC e do provedor VASA após a implantação. Você deve ativar manualmente os serviços VSC e VASA Provider após a implantação.



*Sobre esta tarefa*

Se você estiver implantando uma nova instalação de ferramentas do ONTAP, o provedor VASA será habilitado por padrão. Mas no caso de uma atualização de uma versão anterior das ferramentas do ONTAP, o estado do Fornecedor VASA é mantido e você pode precisar ativar o Fornecedor VASA manualmente.

link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Habilite o provedor VASA para configurar datastores virtuais"]

*Passos*

. Faça login no vSphere Client.
. Selecione *Home* > *Host & clusters*.
. Clique com o botão direito do rato no centro de dados pretendido e, em seguida, clique em *Deploy OVA template*.
. Selecione o método aplicável para fornecer o arquivo de implantação para ferramentas do ONTAP e clique em *Avançar*.
+
|===


| *Localização* | *Ação* 


 a| 
URL
 a| 
Forneça o URL para o arquivo _.ova_ para ferramentas do ONTAP.



 a| 
Pasta
 a| 
Selecione o arquivo _.ova_ para ferramentas ONTAP a partir do local salvo.

|===
. Introduza os detalhes para personalizar o assistente de implementação.
+
link:../deploy/reference_considerations_for_deploying_ontap_tools_for_vmware_vsphere.html["Considerações sobre personalização da implantação"]Consulte para obter detalhes completos.

. Revise os dados de configuração e clique em *Next* para concluir a implantação.
+
À medida que espera que a implementação termine, pode ver o progresso da implementação a partir do separador tarefas.

. Ligue a máquina virtual ONTAP Tools e, em seguida, abra um console da máquina virtual que executa as ferramentas ONTAP.
. Verifique se as ferramentas do ONTAP estão em execução após a conclusão da implantação.
. Se as ferramentas do ONTAP não estiverem registradas em nenhum vCenter Server, use ``\https://appliance_ip:8143/Register.html` para Registrar a instância do VSC.
. Faça logout e faça login novamente no vSphere Client para visualizar as ferramentas do ONTAP implantadas.
+
Pode levar alguns minutos para que o plug-in seja atualizado no vSphere Client.

+
*Solução de problemas:* se você não conseguir visualizar o plug-in mesmo depois de fazer login, você deve limpar o cache do vSphere Client.

+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["Limpe os pacotes de plug-in baixados em cache do vSphere"]




NOTE: Se você estiver usando o ONTAP 9.6 ou anterior, então para visualizar o painel do vVols, baixe e instale os Serviços de API do OnCommand. Mas para o ONTAP 9.7, você não precisa que os Serviços de API da OnCommand sejam registrados no Fornecedor da VASA.

link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Habilite o provedor VASA para configurar datastores virtuais"]

*Informações relacionadas*

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Storage_Software%2FVirtual_Storage_Console_for_VMware_vSphere%2FError_during_fresh_deployment_of_virtual_appliance_for_VSC%252C_VASA_Provider%252C_and_SRA["Erro durante a nova implantação do dispositivo virtual para VSC, provedor VASA e SRA"]
