---
permalink: concepts/concept_privileges_required_for_vsc_tasks.html 
sidebar: sidebar 
keywords:  
summary: 'Diferentes ferramentas do ONTAP para tarefas do VMware vSphere exigem combinações diferentes de Privileges específicas para o console de armazenamento virtual (VSC) e o vCenter Server Privileges nativo.' 
---
= Privileges necessário para tarefas VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diferentes ferramentas do ONTAP para tarefas do VMware vSphere exigem combinações diferentes de Privileges específicas para o VSC (Virtual Storage Console) e o vCenter Server Privileges nativo.

As informações sobre o Privileges necessário para as tarefas do VSC estão disponíveis no artigo 1032542 da base de conhecimento do NetApp.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/How_to_configure_RBAC_for_Virtual_Storage_Console["Como configurar o RBAC para o Virtual Storage Console"]



== Privilégio de nível de produto exigido pelas ferramentas do ONTAP para VMware vSphere

Para acessar as ferramentas do ONTAP para a GUI do VMware vSphere, você deve ter o privilégio de exibição específico do VSC no nível do produto atribuído no nível correto do objeto vSphere. Se você fizer login sem esse privilégio, o VSC exibirá uma mensagem de erro quando você clicar no ícone NetApp e impedirá que você acesse o VSC.

As informações a seguir descrevem o privilégio visualização em nível de produto VSC:

|===


| *Privilégio* | *Descrição* | *Nível de atribuição* 


 a| 
Vista
 a| 
Você pode acessar a GUI do VSC. Este privilégio não lhe permite executar tarefas no VSC. Para executar quaisquer tarefas do VSC, você precisa ter o vCenter Server Privileges nativo e específico do VSC correto para essas tarefas.
 a| 
O nível de atribuição determina quais partes da IU você pode ver. A atribuição do privilégio Exibir no objeto raiz (pasta) permite que você entre no VSC clicando no ícone NetApp.

Você pode atribuir o privilégio Exibir a outro nível de objeto vSphere; no entanto, isso limita os menus VSC que você pode ver e usar.

O objeto raiz é o local recomendado para atribuir qualquer permissão que contenha o privilégio Exibir.

|===