---
permalink: concepts/reference_metrocluster_configurations_supported_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: As ferramentas do ONTAP para VMware vSphere são compatíveis com ambientes que usam configurações MetroCluster IP e FC para ONTAP. A maior parte deste suporte é automático. No entanto, você pode notar algumas diferenças quando você usa um ambiente MetroCluster com VSC e provedor VASA. 
---
= Configurações do MetroCluster compatíveis com as ferramentas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas do ONTAP para VMware vSphere são compatíveis com ambientes que usam configurações MetroCluster IP e FC para ONTAP. A maior parte deste suporte é automático. No entanto, você pode notar algumas diferenças quando você usa um ambiente MetroCluster com VSC e provedor VASA.


NOTE: O SRA não suporta configurações MetroCluster.



== Configurações MetroCluster e VSC

Você deve garantir que o VSC descubra os controladores do sistema de storage no local principal e no local secundário. Normalmente, o VSC descobre automaticamente controladores de storage. Se você estiver usando um LIF de gerenciamento de cluster, é uma boa prática verificar se o VSC descobriu os clusters em ambos os locais. Caso contrário, você pode adicionar manualmente os controladores de storage ao VSC. Você também pode modificar os pares de nome de usuário e senha que o VSC usa para se conetar aos controladores de armazenamento.

Quando ocorre um switchover, os SVMs no local secundário assumem o controle. Estes SVMs têm o sufixo "'-mc" anexado aos seus nomes. Se uma operação de switchover ocorrer enquanto você estiver executando operações como o provisionamento de um datastore, o nome do SVM onde o datastore reside será alterado para incluir o sufixo "'-mc". Esse sufixo é descartado quando o switchback ocorre, e os SVMs no local principal retomam o controle.


NOTE: Se você adicionou SVMs diretas com configuração MetroCluster ao VSC, depois do switchover, a alteração no nome do SVM (a adição do sufixo "'-mc") não será refletida. Todas as outras operações de comutação continuam a ser executadas normalmente.

Quando ocorre um switchover ou um switchback, o VSC pode levar alguns minutos para detectar e descobrir os clusters automaticamente. Se isso acontecer enquanto você estiver executando uma operação do VSC, como o provisionamento de um datastore, você pode ter um atraso.



== Configurações MetroCluster e Fornecedor VASA

O provedor VASA suporta automaticamente ambientes que usam configurações do MetroCluster. O switchover é transparente em ambientes de provedores VASA. Não é possível adicionar SVMs diretas ao Fornecedor VASA.


NOTE: O VASA Provider não acrescenta o sufixo "'-mc" aos nomes dos SVMs no local secundário após uma mudança.
