---
permalink: manage/concept_datastore_reports.html 
sidebar: sidebar 
keywords: Datastore Reports 
summary: Os relatórios do datastore fornecem informações detalhadas sobre os datastores tradicionais e as máquinas virtuais criadas nesses datastores. 
---
= Relatórios do datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os relatórios do datastore fornecem informações detalhadas sobre os datastores tradicionais e as máquinas virtuais criadas nesses datastores.

O dashboard tradicional permite que você analise e identifique possíveis problemas com os datastores e as máquinas virtuais no vCenter Server. Você pode exibir, classificar e exportar relatórios. Os dados do relatório de datastores tradicionais e máquinas virtuais são fornecidos pelo vCenter Server. Mas, devido à introdução do suporte ao datastore com suporte do FlexGroup, algumas métricas como latência, taxa de transferência e IOPS são obtidas do ONTAP.


NOTE: O monitoramento de arquivos não é compatível com datastores FlexGroup configurados em máquinas virtuais de armazenamento direto (SVMs).

O datastore fornece os seguintes relatórios predefinidos:

* Relatório do datastore
* Relatório de Máquina Virtual


*Relatório de armazenamento de dados*

O menu Relatório de datastore fornece informações sobre os seguintes parâmetros para datastores:

* Nome do datastore
* Tipo de armazenamento de dados: NFS ou VMFS
* Estilo de volume
+
O estilo de volume pode ser um volume FlexVol volume ou FlexGroup.

* Espaço livre
* Espaço utilizado
* Espaço total
* Porcentagem de espaço utilizado
* Percentagem de espaço disponível
* IOPS
+
O relatório exibe o IOPS do datastore.

* Latência
+
O relatório exibe as informações de latência do datastore.

+
Você também pode verificar a hora em que o relatório foi gerado. O menu Relatório de armazenamento de dados permite organizar o relatório de acordo com sua exigência e, em seguida, exportar o relatório organizado usando o botão *Exportar para CSV*. Os nomes do datastore no relatório são links que navegam para a guia Monitor do datastore selecionado, onde você pode exibir as métricas de desempenho do datastore.



*Relatório de Máquina Virtual*

O menu Relatório de Máquina Virtual fornece as métricas de desempenho para todas as máquinas virtuais que usam datastores provisionados pelo VSC para um vCenter Server selecionado. As métricas da máquina virtual exibidas nos relatórios de máquina virtual são dados históricos que são coletados a cada 30 minutos para máquinas virtuais em datastores tradicionais. O "último tempo de atualização" e o "próximo tempo de atualização" são adicionados à tabela para fornecer detalhes sobre quando os dados foram coletados e quando será a próxima coleta de dados.

* Nome da máquina virtual
* Nome do datastore
* Estilo de volume
+
O estilo de volume pode ser um volume FlexVol volume ou um volume FlexGroup.

* Fonte
+
A fonte para reunir detalhes da máquina virtual pode ser o ONTAP ou o vCenter Server.

* Latência
+
O relatório exibe a latência das máquinas virtuais em todos os datastores associados às máquinas virtuais.

* IOPS
* Taxa de transferência
* Capacidade comprometida
+
O relatório exibe o valor da capacidade comprometida de uma máquina virtual.

* Host
+
O relatório exibe os sistemas host nos quais a máquina virtual está disponível.

* Tempo de atividade
+
O relatório exibe a hora em que a máquina virtual está ligada e está disponível em um host ESXi.

* Estado de alimentação
+
O relatório mostra se a máquina virtual está ligada ou desligada.



Cada nome de máquina virtual no relatório é um link para a guia Monitor da máquina virtual selecionada. Você pode classificar o relatório de máquina virtual de acordo com sua exigência e exportar o relatório em um arquivo .CSV e salvar o relatório em seu sistema local. O carimbo de data/hora do relatório também é anexado ao relatório salvo.

Para máquinas virtuais com suporte do FlexGroup volumes, quando a nova máquina virtual é ativada, os arquivos são registrados para monitoramento no ONTAP. As métricas históricas de latência, taxa de transferência e IOPS são obtidas quando os relatórios de VM são acessados do ONTAP.
