---
permalink: manage/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: Você pode usar as ferramentas do ONTAP para VMware vSphere para definir credenciais padrão para um sistema de armazenamento no vCenter Server. 
---
= Definir credenciais padrão para sistemas de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar as ferramentas do ONTAP para VMware vSphere para definir credenciais padrão para um sistema de armazenamento no vCenter Server.

*O que você vai precisar*

Você deve ter selecionado o vCenter Server que deseja usar para criar credenciais padrão.

*Sobre esta tarefa*

Se você configurar credenciais padrão para sistemas de storage, o Virtual Storage Console (VSC) usará essas credenciais para fazer login em um sistema de storage que o VSC acabou de descobrir. Se as credenciais padrão não funcionarem, você deverá fazer login manualmente no sistema de storage. O VSC e o SRA são compatíveis com a adição de credenciais do sistema de storage no nível do cluster ou SVM. Mas o provedor VASA só funcionará com credenciais de cluster.

*Passos*

. Na página inicial de Ferramentas do ONTAP, clique em *Configurações* > *Configurações administrativas* > *Configurar credenciais padrão para o sistema de armazenamento*.
. Na caixa de diálogo credenciais padrão do sistema de armazenamento, insira o nome de usuário e a senha do sistema de armazenamento.
+
As credenciais do controlador de armazenamento são atribuídas no ONTAP com base no nome de utilizador e no par de palavras-passe. As credenciais do controlador de storage podem ser a conta de administrador ou uma conta personalizada que usa o controle de acesso baseado em funções (RBAC).

+
Não é possível usar o VSC para alterar as funções associadas ao nome de usuário e ao par de senhas do controlador de armazenamento. Para modificar ou criar uma nova função de usuário do ONTAP para uso com as ferramentas do ONTAP, você pode usar o Gerenciador do sistema.

+
Consulte a seção "Configurando funções de usuário e Privileges" no ONTAP Guia de implantação e configuração do VMware vSphere para a versão 9,7_.

. Clique em *OK* para salvar as credenciais padrão.


Se você atualizou as credenciais do sistema de armazenamento porque um sistema de armazenamento relatou o status de "Falha de autenticação", clique na opção *REDESCOBRIR TUDO* disponível na página sistemas de armazenamento. Ao fazer isso, o VSC tenta se conetar ao sistema de storage usando as novas credenciais.
